### ISSUE TITLE
Convert baseline test data from JSON to CovJSON

### ISSUE THREAD

**Issue by hemphilc** [RiverHendriksen/bes#13]
The following test data set baseline files need to be converted to CovJSON data and metadata from JSON.

- [abstract_object_test_DATA.covjson.baseline](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/unit-tests/baselines/abstract_object_test_DATA.covjson.baseline)
- [abstract_object_test_METADATA.covjson.baseline](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/unit-tests/baselines/abstract_object_test_METADATA.covjson.baseline)
- [instance_object_test_DATA.covjson.baseline](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/unit-tests/baselines/instance_object_test_DATA.covjson.baseline)
- [instance_object_test_METADATA.covjson.baseline](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/unit-tests/baselines/instance_object_test_METADATA.covjson.baseline)

**Comment by rrimer07** [comment]
Do we need to convert these? or can we replace them entirely?

**Comment by hemphilc** [comment]
Replace them entirely.

- Rename the files
- Remove JSON test data/metadata sets
- Add CovJSON test datameta/data sets

**Comment by hemphilc** [comment]
More unit test work is to be done, but I think this issue is ok to close
