### ISSUE TITLE
Implement Config and Makefile for covjson Module

### ISSUE THREAD

**Issue by RiverHendriksen** [RiverHendriksen/bes#2]
Since besCreateModule is no longer supported we cannot use it to have the besframework point to our new module. As such we need to figure out where the config & make file is in BES so as to have it point to our coverageJSON directory.

**Comment by rrimer07** [comment]
I think we need to change this file to include the make files in the new modules directory.
https://github.com/RiverHendriksen/bes/blob/master/configure.ac
Then run autoconf with it to create the configuration.

beyond that I think we need to change this makefile to include the new module also
https://github.com/RiverHendriksen/bes/blob/master/modules/Makefile.am
Not entirely sure though, ill try messing with it tomorrow if no one else has by then.

**Comment by rrimer07** [comment]
Course im not even sure if thats how we should be going about it since this stuff uses automake

**Comment by RiverHendriksen** [comment]
This looks correct, we should test it

**Comment by rrimer07** [comment]
Found this which seems useful.
https://stackoverflow.com/questions/26832264/confused-about-configure-script-and-makefile-in

I made the changes mentioned above but it runs into errors saying it cant find the makefile.in, I will mess with it some more

**Comment by rrimer07** [comment]
I get errors like this even on master when I try doing autoreconf for the bes

modules/Makefile.am:9: warning: SUBDIRS multiply defined in condition TRUE ...
modules/Makefile.am:7: ... 'SUBDIRS' previously defined here
autoreconf: automake failed with exit status: 1

**Comment by rrimer07** [comment]
This seems to be working now in this branch. It is untested though. We need to find a way to test out the module now that it was able to be created through automake. Best way would probably through calling the bes with the command line but I cant recall how.

**Comment by rrimer07** [comment]
This seems to be completed now, needs to be tested by making changes to the olfs so we can call the module.

The changes will be in the form of replicating some of these files found at the following link:
https://github.com/RiverHendriksen/olfs/search?utf8=%E2%9C%93&q=ijsn&type=

This will allow us to call the mudule through something like "DATASETURL.covjson" like the current implementation of "DATASETURL.json"

Once this is done we can try calling the module to make sure it was built correctly.

**Comment by RiverHendriksen** [comment]
This has been pulled to master
