### ISSUE TITLE
Modify FoDapCovJsonTransform files to handle CovJSON

### ISSUE THREAD

**Issue by hemphilc** [RiverHendriksen/bes#4]
The following files need to be adapted to handle CovJSON:

- [FoDapCovJsonTransform.cc](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransform.cc)
- [FoDapCovJsonTransform.h](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransform.h)

**Comment by hemphilc** [comment]
We need to be able to recognize the data that through its metadata, so we can choose to only pull out parts of the data rather than the whole data set. We will want to search for keywords in the metadata that would allude to the standards it follows. Some data sets will follow data standards which we can find if we look in the metadata, and then it will be much easier to pull in and separate out parts of the data.
We need to be able to recognize things like ‘east’, ‘long’, ‘x’ and be able to interpret the different variables to bring it into a coverage.

- [CovJSON Specs](https://covjson.org/spec/)

**Comment by rrimer07** [comment]
Might be good to have some form of uml or something to help us understand the transform files. Ill look into making this today.

**Comment by hemphilc** [comment]
FoDapCovJsonTransform method walkthrough can be found [here](https://drive.google.com/open?id=0B58Ue6byhnohcVlHd0ZlUXd5YWUyX3NWQ3NNdHdzTTIyN29v).

**Comment by hemphilc** [comment]
Completely modified FoDapCovJsonTransform - added a number of new functions, and modified almost every existing function there was. There are two small bugs as of right now, but this issue is complete. Pend closing this issue.

**Comment by hemphilc** [comment]
Also added full function documentation headers for all functions in FoDapCovJsonTransform.cc, as well as FoDapCovJsonValidation.cc.

**Comment by hemphilc** [comment]
Fixed line spacing bugs -- merged branch issue-#5 to master. Closing issue.
