### ISSUE TITLE
Modify FoDapCovJsonTransmitter files to handle CovJSON

### ISSUE THREAD

**Issue by hemphilc** [RiverHendriksen/bes#5]
The following files need to be adapted to handle CovJSON:

- [FoDapCovJsonTransmitter.cc](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransmitter.cc)
- [FoDapCovJsonTransmitter.h](https://github.com/RiverHendriksen/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransmitter.h)

**Comment by RiverHendriksen** [comment]
duplicate
